// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDg8cHttZ4ZXx5o-VYpZKIe-vf3AvQdHk',
    appId: '1:570530684308:web:7fed25433caa8ade65c381',
    messagingSenderId: '570530684308',
    projectId: 'instax-62b5b',
    authDomain: 'instax-62b5b.firebaseapp.com',
    storageBucket: 'instax-62b5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv2UlnOnQ2rIXAKT9HwN4eLakJ26OuNWA',
    appId: '1:570530684308:android:ae4d0bd4d5edc92c65c381',
    messagingSenderId: '570530684308',
    projectId: 'instax-62b5b',
    storageBucket: 'instax-62b5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASZs0HhJe4MEQGjFuR4pQP9tbffNqTM6s',
    appId: '1:570530684308:ios:a7e5372600b12ca965c381',
    messagingSenderId: '570530684308',
    projectId: 'instax-62b5b',
    storageBucket: 'instax-62b5b.appspot.com',
    iosBundleId: 'ipg.elite.instax',
  );
}
